import { BLIND_QUERY_CANDIDATES } from "./modelRetrievalBlindQueries.ts";
import type { GoldenPair } from "./modelRetrievalGolden.ts";

const labels: Array<[number, string[], string?]> = [
  [0, ["fire-headquarters"], "civic"],
  [1, ["central-library-wave"], "civic"],
  [2, ["bus-stop-shelter"], "furniture"],
  [3, ["ambulance-emergency"], "vehicles"],
  [4, ["olympic-stadium-arena"], "civic"],
  [5, ["passenger-jetway-bridge"], "aviation"],
  [6, ["marina-clubhouse", "ocean-observation-pier"], "civic"],
  [7, ["highway-overpass-span"], "bridges"],
  [8, ["signature-pedestrian-skyway", "pedestrian-flat-bridge"], "bridges"],
  [9, ["sunken-rail-corridor"], "roads"],
  [10, ["airport-control-tower"], "aviation"],
  [12, ["opera-symphony-hall"], "civic"],
  [13, ["contemporary-art-wing", "community-art-center"], "civic"],
  [14, ["municipal-courthouse"], "civic"],
  [15, ["parliament-rotunda", "town-hall-classic"], "civic"],
  [17, ["stainless-trash-recycler", "garbage-compactor-truck"]],
  [21, ["aircraft-hangar-dome"], "aviation"],
  [24, ["artisan-workshop"], "buildings"],
  [28, ["scout-camp-lodge"], "civic"],
  [30, ["tennis-center-grandstand"], "civic"],
  [31, ["olympic-aquatic-centre", "public-pool-complex"], "civic"],
  [33, ["youth-recreation-center"], "civic"],
  [34, ["formal-rose-garden", "wildflower-swathe"], "vegetation"],
  [35, ["civic-monument-plaza", "triumphal-arch"], "civic"],
  [36, ["cathedral-spire"], "civic"],
  [43, ["botanical-orangery", "biome-botanical-domes"], "civic"],
  [49, ["public-telescope"], "furniture"],
  [50, ["container-cargo-ship"], "maritime"],
  [51, ["rowboat-skiff"], "maritime"],
  [52, ["commercial-trawler", "lobster-fishing-boat"], "maritime"],
  [53, ["deepsea-submersible-tender"], "maritime"],
  [54, ["search-rescue-helicopter"], "aviation"],
  [55, ["ambulance-emergency"], "vehicles"],
  [56, ["fire-ladder-truck"], "vehicles"],
  [57, ["city-transit-bus", "electric-articulated-bus"], "vehicles"],
  [58, ["heavy-freight-locomotive"], "vehicles"],
  [59, ["city-bicycle-commuter"], "vehicles"],
  [61, ["ancient-oak", "european-beech"], "vegetation"],
  [62, ["boxwood-ball", "manicured-boxwood-hedge"], "vegetation"],
  [63, ["plaza-grand-fountain", "tiered-marble-fountain"], "civic"],
  [64, ["civic-tower-clock", "decorative-clock-pillar"]],
  [65, ["street-vendor-cart"], "furniture"],
  [66, ["modern-waste-bin", "stainless-trash-recycler"], "furniture"],
  [67, ["stone-drinking-fountain"], "furniture"],
  [68, ["emergency-phone-pillar"], "furniture"],
  [69, ["boom-barrier-gate"], "boundary"],
  [73, ["temporary-construction-barrier"], "boundary"],
  [74, ["info-bulletin-board"], "furniture"],
  [75, ["traffic-stop-light"], "furniture"],
  [78, ["pedestrian-spiral-ramp"], "bridges"],
];

export const BLIND_LABELED_CANDIDATES: GoldenPair[] = labels.map(([index, expected, category]) => ({
  id: `blind-${String(index + 1).padStart(2, "0")}`,
  query: BLIND_QUERY_CANDIDATES[index],
  expected,
  category,
  type: "semantic_zero_overlap",
  split: "held_out",
  description: "Answer-free candidate labeled after query freeze",
}));
