// Answer-free candidate queries. These were frozen before candidate authors
// inspected the registry to select expected assets. Target labels belong in a
// separate file and commit so authorship order remains auditable.

export const BLIND_QUERY_CANDIDATES = [
  "shelter where municipal rescuers keep their engines",
  "quiet building for borrowing books and studying",
  "covered place where commuters wait for rail service",
  "facility that treats injured residents overnight",
  "venue where crowds watch competitive field events",
  "structure where aircraft board travellers",
  "waterside platform used to moor recreational vessels",
  "crossing that carries automobiles above a river",
  "crossing reserved for people walking above traffic",
  "underground route carrying metropolitan trains",
  "tower used to direct arriving aircraft",
  "building where pupils attend daily lessons",
  "hall used for live orchestral performances",
  "indoor venue displaying paintings and sculpture",
  "place where judges hear criminal cases",
  "municipal headquarters for elected representatives",
  "secure building holding convicted offenders",
  "facility where household refuse is processed for reuse",
  "plant that cleans sewage before discharge",
  "building containing turbines that produce electricity",
  "warehouse kept cold for perishable merchandise",
  "large shed for repairing flying machines",
  "multistorey structure for leaving automobiles",
  "roadside business selling fuel to motorists",
  "place where mechanics repair damaged automobiles",
  "shop selling medicine and health supplies",
  "marketplace with many vendors beneath one roof",
  "lodging where travellers rent rooms overnight",
  "building offering temporary beds for young travellers",
  "outdoor venue where spectators watch batters and pitchers",
  "enclosed court used for racket matches",
  "aquatic venue with lanes for competitive swimmers",
  "winter venue where skaters pursue a puck",
  "outdoor area containing swings and climbing equipment",
  "landscaped public space for walking among flowers",
  "memorial column commemorating a historic event",
  "religious building featuring a tall bell structure",
  "Islamic place of worship with slender prayer towers",
  "Jewish place of worship for communal prayer",
  "ceremonial building where bodies are cremated",
  "remote structure warning ships away from rocks",
  "fortified residence surrounded by defensive walls",
  "agricultural building used to store hay",
  "glass enclosure used to cultivate plants in winter",
  "tall agricultural vessel storing harvested grain",
  "machine that converts moving air into electricity",
  "array that converts daylight into electrical power",
  "raised cylindrical container supplying municipal water",
  "communications mast carrying broadcast equipment",
  "large circular antenna used to observe space",
  "vessel that transports boxed freight across oceans",
  "small craft propelled by a person using paddles",
  "working vessel that harvests seafood",
  "submersible military vessel travelling beneath waves",
  "rotorcraft used to evacuate injured people",
  "road vehicle carrying patients to urgent treatment",
  "heavy road vehicle that pumps water onto fires",
  "long road vehicle carrying urban commuters",
  "rail vehicle hauling merchandise between cities",
  "two-wheeled pedal vehicle parked beside a street",
  "small winged animal perched in an urban tree",
  "large shade plant lining a residential avenue",
  "low decorative plants bordering a public walkway",
  "stone basin spraying water into a civic square",
  "upright timepiece visible from a town plaza",
  "covered stand selling newspapers beside a pavement",
  "public fixture where pedestrians discard litter",
  "street fixture providing drinking water to passersby",
  "small enclosure where callers once used telephones",
  "striped roadside marker blocking vehicle access",
  "temporary framework surrounding a building under repair",
  "machine lifting materials on a construction site",
  "large metal container used for building debris",
  "portable shelter used by workers at a job site",
  "illuminated roadside panel displaying advertisements",
  "vertical signal controlling automobile movement",
  "painted marker showing where people may cross a road",
  "covered passage connecting separate buildings overhead",
  "moving staircase carrying shoppers between floors",
  "enclosed platform carrying occupants between storeys",
] as const;
