// =============================================================================
// P4.6 -- ONE COMMAND FOR EVERY GENERATED CLAIM
//
// Three generated claims -- the test counts, the city summary, and (through
// it) the building count -- have each drifted independently this week,
// every single time found by accident while chasing something else (most
// recently: fixing the test-count knot surfaced a stale building count that
// had nothing to do with it). They drift independently because they are
// regenerated by different scripts, run at different times, by whoever
// happened to be touching whichever one. This does not replace
// scripts/gen-city-summary.mjs or scripts/gen-test-count.mjs -- it calls
// them, in one place, and reports what each one actually changed, so
// regenerating "the claims" is one command instead of remembering which
// scripts exist.
//
//   node scripts/gen-claims.mjs
//   node scripts/gen-claims.mjs --node-log <path> --worker-log <path>
//     (passed straight through to gen-test-count.mjs's own flags -- see
//     that script's header for why they exist: running the full suite
//     twice, once for this and once for a caller's own verification,
//     doubles the memory this project has already been burned by.)
// =============================================================================
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function readOrNull(path) {
  try { return readFileSync(path, "utf8"); } catch { return null; }
}

const TRACKED = [
  { label: "src/citySummary.generated.ts", path: join(ROOT, "src", "citySummary.generated.ts") },
  { label: "test/testCount.generated.json", path: join(ROOT, "test", "testCount.generated.json") },
  { label: "public/index.html", path: join(ROOT, "public", "index.html") },
];
const before = TRACKED.map((t) => readOrNull(t.path));

console.log("Regenerating src/citySummary.generated.ts (scripts/gen-city-summary.mjs)...");
execFileSync(process.execPath, [join(ROOT, "scripts", "gen-city-summary.mjs")], { cwd: ROOT, stdio: "inherit" });

console.log("\nRegenerating test/testCount.generated.json and public/index.html's test-count claim (scripts/gen-test-count.mjs)...");
const passthroughFlags = ["--node-log", "--worker-log"];
const extra = [];
for (const flag of passthroughFlags) {
  const i = process.argv.indexOf(flag);
  if (i !== -1 && process.argv[i + 1]) extra.push(flag, process.argv[i + 1]);
}
let testCountExit = 0;
try {
  execFileSync(process.execPath, [join(ROOT, "scripts", "gen-test-count.mjs"), ...extra], { cwd: ROOT, stdio: "inherit" });
} catch (e) {
  // gen-test-count.mjs's own non-zero exit means it correctly refused to
  // publish a stale-suite claim -- not a failure of THIS script, which
  // still needs to report what DID change (the city summary above,
  // and the JSON record gen-test-count.mjs writes even on a refusal).
  testCountExit = e.status ?? 1;
}

console.log("\n--- what changed ---");
let anyChanged = false;
TRACKED.forEach((t, i) => {
  const after = readOrNull(t.path);
  const changed = after !== before[i];
  if (changed) anyChanged = true;
  console.log(`${changed ? "CHANGED" : "unchanged"}  ${t.label}`);
});
if (!anyChanged) console.log("(nothing changed -- every generated claim already agreed with a fresh measurement)");

if (testCountExit !== 0) {
  console.log(
    "\ngen-test-count.mjs exited non-zero -- see its own output above for why. " +
    "Both a correct refusal (the suite has real failures beyond its own narrow " +
    "exemption, so the page's claim was not published) and a genuine tool " +
    "failure (could not read the runner's output, missing markup, ...) use the " +
    "same exit code, and this script does not try to guess which; read the " +
    "printed reason, do not assume it was the benign case.",
  );
}

console.log(
  "\nCLAUDE.md's own \"How to verify\" line is NOT regenerated by anything -- " +
  "no script writes prose in a document meant for a person to read. If " +
  "test/testCount.generated.json's nodeTests/workerTests changed above, " +
  "update CLAUDE.md's `npm test # N node tests + M worker tests` line by hand " +
  "to match, or test/claudeMdIsCurrent.test.ts will catch the drift.",
);

// Faithfully propagated, not swallowed: gen-test-count.mjs's exit code is the
// only signal a caller has for "did everything this script tried to do
// actually succeed" -- collapsing it to 0 here would hide a genuine tool
// failure behind "regeneration complete".
process.exit(testCountExit);
